name: Run Textlint
on:
  pull_request:
    paths:
      - 'work/**/*.md'
      - 'private/**/*.md'
permissions:
  pull-requests: write

jobs:
  textlint:
    name: TextLint Check
    runs-on: ubuntu-latest
    env:
      MARKDOWN_PATHS: 'work/**/*.md private/**/*.md'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          npm install

      - name: Run textlint and capture result
        id: textlint
        run: |
          if ! npx textlint $MARKDOWN_PATHS > .textlint.log 2>&1; then
            echo "Textlint failed"
            echo "failed=true" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR if lint fails
        if: steps.textlint.outputs.failed == 'true'
        run: |
          gh pr comment "$PR_URL" --body "$(cat .textlint.log)"
          exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
