name: Run Textlint
on:
  pull_request:
    paths:
      - 'work/**/*.md'
      - 'private/**/*.md'
permissions:
  pull-requests: write

jobs:
  textlint:
    name: TextLint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          npm install

      - name: Run textlint and capture result
        run: |
          npx textlint work/**/*.md private/**/*.md > .textlint.log 2>&1 || echo $? > .textlint-exitcode

      - name: Comment on PR if lint fails
        if: always()
        run: |
          if [ -s .textlint.log ] && [ -f .textlint-exitcode ]; then
            gh pr comment "$PR_URL" --body "$(cat .textlint.log)" --edit-last
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
